-- seed database with records
-- SCOPE_IDENTITY returns last identity created in same session in same scope
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Bill', 'Burr', 'billburr@laughsohardihurt.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230000', 'home')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Jerry', 'Seinfeld', 'jerryseinfeld@laughsohardihurt.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230001','home')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230002','mobile')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Kevin', 'Hart', 'kevinhart@superentertaining.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230003','mobile')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Joe', 'Rogan', 'joerogan@crazyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230004','office')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230005','mobile')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Dusty', 'Slay', 'dustyslay@eyewateringlyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230006','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Jeff', 'Foxworthy', 'jefffoxworthy@superfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230007','home')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Norm', 'Macdonald', 'normmacdonald@dryandhumorous.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230008','office')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230009','home')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230009','moblie')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Bill', 'Hicks', 'billhicks@superentertaining.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230010','home')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Lewis', 'Black', 'lewisblack@laughsohardihurt.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230011','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Don', 'Rickles', 'donrickles@obnoxiouslyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230012','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Rodney', 'Dangerfield', 'rodneydangerfield@obnoxiouslyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230013','office')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230014','home')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Chris', 'Rock', 'chrisrock@crazyfunny.com')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Dave', 'Chappelle', 'davechappelle@crazyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230015','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Richard', 'Pryor', 'richardpryor@laughsohardihurt.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230016','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Alan', 'King', 'alanking@eyewateringlyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230017','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Steve', 'Harvey', 'steveharvey@crazyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230018','mobile')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230019','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('John', 'Mulaney', 'johnmulaney@crazyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230020','mobile')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Brian', 'Regan', 'brianregan@eyewateringlyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230021','mobile')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230022','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Sam', 'Kinison', 'samkinison@eyewateringlyfunny.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230023','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Jonathan', 'Winters', 'jonathanwinters@laughsohardihurt.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230024','office')
INSERT INTO dbo.Person (FirstName, LastName, Email) VALUES ('Bob', 'Newhart', 'bobnewhart@dryandhumorous.com')
INSERT INTO dbo.Phone  (PersonId, Phone, PhoneType) VALUES (SCOPE_IDENTITY(), '6191230025','office')
